name: myapp
description: "Um APP para Controle de Tarefas do Dia"."

# Evita a publicação acidental do pacote no pub.dev.
publish_to: 'none'

# Versão do app (major.minor.patch+build_number)
version: 1.0.0+1

# Definição de ambiente
environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependências principais do projeto
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11 # Localização de diretórios no dispositivo
  cupertino_icons: ^1.0.8 # Ícones estilo iOS
  get: ^4.6.1 # Gerenciamento de estado
  firebase_core: ^2.24.2 # Configuração do Firebase
  cloud_firestore: ^4.13.6 # Banco de dados Firestore
  firebase_auth: ^3.3.3 # Autenticação com Firebase
  retrofit: ^3.0.1
  dio: ^5.3.2
  json_annotation: ^4.8.1
  dio: ^4.0.0
  json_annotation: ^4.0.1

# Dependências de desenvolvimento e ferramentas auxiliares
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Regras recomendadas para boas práticas
  mockito: ^5.4.1 # Biblioteca para criação de mocks
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

# Configurações específicas do Flutter
flutter:
  uses-material-design: true
  # Adicione recursos como imagens ou fontes, se necessário:
  # assets:
  #   - images/example.png
